insert into cidade (nome, uf) values ('Tubarão', 'SC');
insert into cidade (nome, uf) values ('Laguna', 'SC');
insert into cidade (nome, uf) values ('Gravatal', 'SC');
insert into cidade (nome, uf) values ('Capivari de Baixo', 'SC');
insert into cidade (nome, uf) values ('Porto Alegre', 'RS');
insert into cidade (nome, uf) values ('São Paulo', 'SP');
insert into cliente (nome, genero, cidade) values ('Maria', 'F', 1);
insert into cliente (nome, genero, cidade) values ('João', 'M', 5);
insert into cliente (nome, genero, cidade) values ('Pedro', 'M', 3);
insert into cliente (nome, genero, cidade) values ('José', 'M', 4);
insert into cliente (nome, genero, cidade) values ('Ana', 'F', 2);
insert into cliente (nome, genero, cidade) values ('Amanda', 'F', 5);
insert into cliente (nome, genero, cidade) values ('Carlos', 'M', 4);